[package]
name = "vibe-pkg"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
license = "MIT"
description = "The signed package manager for vibeOS"
repository = "https://github.com/vibedOS/vibe-pkg"
autobins = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "vibe-pkg"
path = "src/main.rs"
test = false
bench = false

[[bin]]
name = "vibe-pkg-build"
path = "src/bin/vibe-pkg-build.rs"
required-features = ["builder"]

[features]
builder = []

[dependencies]
ed25519-dalek = { version = "2.2.0", default-features = false, features = ["fast"] }
vibe-net = { git = "https://github.com/vibedOS/vibe-net", rev = "add7630834acfacb404640279a74dfd8f36a4923" }
vibe-rt = { git = "https://github.com/vibedOS/vibe-rt", rev = "a410593afbf1b6047a1cea3a47f2aa30d61a9466" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = "symbols"
